import type { GuidanceContent, GuidanceId, HelpTopic, TourStep } from "./types";

export const DISCLAIMER =
  "GreenFleet is an academic decision-support prototype. Guidance explains how to use the model and does not constitute financial, investment, engineering or regulatory advice.";

export const WELCOME = {
  title: "Welcome to GreenFleet",
  text: "GreenFleet helps logistics entrepreneurs compare Diesel, Battery Electric and Biofuel vehicles using their own operating, cost, infrastructure and environmental assumptions.",
  journey: [
    { title: "Describe Your Fleet", text: "Fleet size, distance, days and payload." },
    { title: "Enter Technology Assumptions", text: "Diesel, battery electric and biofuel inputs." },
    { title: "Run the Assessment", text: "Review your inputs, then calculate." },
    { title: "Compare Commercial Viability", text: "Cost, operation, emissions and a classification." },
  ],
} as const;

export const HOW_GREENFLEET_WORKS = [
  "Describe your current fleet and operations.",
  "Enter diesel, electric and biofuel assumptions.",
  "Add finance, infrastructure and environmental assumptions.",
  "Review and run the assessment.",
  "Compare costs, operational feasibility and emissions.",
  "Review GreenFleet's transparent commercial classification.",
] as const;

export const TOUR_STEPS: readonly TourStep[] = [
  { id: "overview", title: "Overview", where: "Sidebar: Overview", href: "/overview", body: "Your starting page. It shows how far you have got and how the whole journey fits together. Your work is saved in this browser." },
  { id: "new", title: "New Assessment", where: "Sidebar: New Assessment", href: "/assessment/business", body: "Start or continue an assessment here. Nothing is pre-filled except a labelled demo you can load to see how the tool works." },
  { id: "wizard", title: "The six steps", where: "New Assessment", href: "/assessment/business", body: "Business and fleet, diesel, battery electric, biofuel, finance and infrastructure, then review. Essential inputs come first. Advanced assumptions are collapsed and optional." },
  { id: "review", title: "Review and calculate", where: "Step 6: Review & Calculate", href: "/assessment/review", body: "Check every assumption and see what is missing. Then run the assessment. GreenFleet never fills a blank with an invented value." },
  { id: "results", title: "Results", where: "Sidebar: Results", href: "/results", body: "Four separate answers: economic performance, operational feasibility, environmental performance and a commercial classification against diesel. Each has a help button." },
  { id: "method", title: "Methodology", where: "Sidebar: Methodology", href: "/methodology", body: "Every formula, assumption and decision rule, for anyone who wants to check the work." },
  { id: "upcoming", title: "Sensitivity and Scenarios", where: "Sidebar: Sensitivity Analysis, Saved Scenarios", href: "/sensitivity", body: "These are upcoming tools. Sensitivity analysis will show how changing key assumptions affects the result, and scenarios will let you keep and compare cases. They are not available yet." },
];

const FINANCE_NOTE = "GreenFleet's primary project NPV and TCO evaluate the underlying vehicle and infrastructure investment independently of debt financing. Loan information is stored separately and is not double-counted in project economics.";

export const GUIDANCE: Record<GuidanceId, GuidanceContent> = {
  home: {
    id: "home",
    title: "Welcome to GreenFleet",
    shortDescription: "What GreenFleet does and how to start.",
    whatYouAreDoing: "You are at the start. From here you can begin an assessment, continue one, or load a labelled demo.",
    whatGreenFleetDoes:
      "GreenFleet compares a diesel baseline, battery electric vehicles and biofuel or alternative-fuel vehicles. It looks at four things: economic performance, operational feasibility, environmental performance and commercial viability. It uses only the assumptions you enter.",
    whyItMatters: "A green vehicle is not automatically the better business choice, and the cheapest vehicle may not suit your routes. Looking at each question separately keeps the answer honest.",
    tips: ["Your work is saved in this browser, with no account.", "The demo values are illustrative. They show how the tool works and say nothing about real costs."],
    warnings: ["GreenFleet does not supply live market prices. It does not guarantee investment outcomes."],
    whatHappensNext: "Start with Business & Fleet, then describe each technology.",
    links: [{ label: "Start an assessment", href: "/assessment/business" }, { label: "View full methodology", href: "/methodology" }],
  },
  "assessment.business": {
    id: "assessment.business",
    title: "Step 1: Business & Fleet",
    shortDescription: "Describe the transport work every option must do.",
    whatYouAreDoing: "Describe the logistics operation GreenFleet will analyse.",
    whatYouNeed: ["Fleet size", "Vehicle category", "Operating distance per day or per year", "Operating days per year", "Payload (capacity and average)", "Route information, if you know it", "Analysis horizon in years"],
    whyItMatters: "These values define the transport duty that the Diesel, BEV and Biofuel alternatives must perform. All three are compared on the same duty.",
    tips: ["Choose daily or annual distance, whichever you know.", "Route distance is optional. It lets GreenFleet check whether one route fits a battery electric range."],
    relatedTerms: ["analysisHorizon", "utilisation", "payload"],
    whatHappensNext: "You will describe the diesel baseline.",
  },
  "assessment.diesel": {
    id: "assessment.diesel",
    title: "Step 2: Diesel Baseline",
    shortDescription: "The conventional vehicle the others are compared with.",
    whatYouAreDoing: "Diesel is the comparison baseline. GreenFleet uses it to determine whether BEV or Biofuel creates an economic advantage under the same transport duty.",
    whatYouNeed: ["Vehicle acquisition price", "Fuel efficiency", "Diesel price", "Annual maintenance", "Useful life", "Residual (resale) value"],
    whyItMatters: "Every result is a difference from this baseline, so its inputs matter as much as the alternatives' inputs. Diesel is a reference case. It is not treated as better or worse.",
    tips: ["Enter fuel efficiency as km per litre or litres per 100 km. They describe the same thing.", "Leave price escalation blank if you have no view. Nothing is assumed."],
    relatedTerms: ["fuelEfficiency", "residualValue", "escalation"],
    whatHappensNext: "Next, you will describe the battery-electric alternative.",
  },
  "assessment.bev": {
    id: "assessment.bev",
    title: "Step 3: Battery Electric",
    shortDescription: "The electric alternative, its energy cost and how well it suits your routes.",
    whatYouAreDoing: "You are describing the battery-electric alternative to compare with the diesel baseline.",
    whatYouNeed: ["Vehicle acquisition price", "Electricity consumption", "Electricity tariff", "Usable range", "Maintenance", "Charging losses", "Charging opportunity and charging downtime", "Payload impact", "Battery replacement assumption"],
    whyItMatters: "Range and charging inputs affect operational feasibility, while price and energy inputs affect commercial economics. They are judged separately.",
    tips: ["Enter the usable range you want GreenFleet to use for route compatibility, not a brochure figure.", "If you do not know whether the battery will be replaced, choose Unknown. It is flagged as an uncertainty, not assumed."],
    relatedTerms: ["energyConsumption", "usableRange", "chargingLosses", "chargingDowntime", "payloadReduction", "batteryReplacement"],
    whatHappensNext: "Next, you will configure the biofuel alternative.",
  },
  "assessment.biofuel": {
    id: "assessment.biofuel",
    title: "Step 4: Biofuel",
    shortDescription: "The biofuel or alternative-fuel pathway.",
    whatYouAreDoing: "You are describing the biofuel or alternative-fuel pathway to compare with diesel.",
    whatYouNeed: ["Fuel pathway", "Vehicle purchase or conversion", "Fuel efficiency", "Fuel price", "Fuel availability", "Refuelling burden (extra distance and downtime)", "Special infrastructure", "Maintenance"],
    whyItMatters: "Fuel availability affects operational feasibility independently from financial attractiveness. A cheap fuel you cannot reliably buy is not a workable option.",
    tips: ["Enter the price of the fuel as you buy it. For a blend, that is the price of the blend.", "Choose the pathway first. Not every engine can use every fuel."],
    relatedTerms: ["biofuelBlend", "fuelEfficiency", "fuelAvailability"],
    whatHappensNext: "Next, you will add finance, infrastructure and environmental assumptions.",
  },
  "assessment.finance": {
    id: "assessment.finance",
    title: "Step 5: Finance & Infrastructure",
    shortDescription: "Discount rate, incentives, infrastructure and emission factors.",
    whatYouAreDoing: "This section describes the economic assumptions and supporting infrastructure used in the assessment.",
    whatYouNeed: ["Discount rate", "Financing details, if any", "Incentives you are confident of receiving", "Charging infrastructure", "Biofuel infrastructure", "Emission factors, if you want an environmental comparison"],
    whyItMatters: "The discount rate sets how future costs are valued today. Infrastructure is a real cost of the alternatives. Emission factors are optional and only affect the environmental comparison.",
    warnings: [FINANCE_NOTE, "GreenFleet supplies no emission factors. Enter figures from a source you can name."],
    tips: ["Enter the discount rate as a percentage. Enter 10 for 10%.", "Leave emission factors blank if you do not have them. The environmental result will show as unavailable, and the commercial classification is still produced."],
    relatedTerms: ["discountRate", "incentive", "infraSharing", "emissionFactor", "co2e"],
    whatHappensNext: "Next, you will review every assumption before calculating.",
  },
  "assessment.review": {
    id: "assessment.review",
    title: "Step 6: Review & Calculate",
    shortDescription: "Check your assumptions, then run the assessment.",
    whatYouAreDoing: "Review your assumptions before calculation. GreenFleet's results are only as reliable as the inputs supplied.",
    whatGreenFleetDoes: "When you run the assessment, GreenFleet will calculate economic performance, operational feasibility, environmental performance where emission factors are available, and commercial viability.",
    definitions: [
      { term: "USER INPUT", text: "A value you entered." },
      { term: "DERIVED VALUE", text: "Worked out from your other inputs. Not entered directly." },
      { term: "MISSING / EXCLUDED", text: "Not entered, or deliberately left out of the primary calculation." },
      { term: "ILLUSTRATIVE ASSUMPTION", text: "A placeholder from the demo. Not current market data." },
      { term: "SOURCED VALUE", text: "You named a source for this number." },
      { term: "MODEL CONVENTION", text: "A fixed rule of the calculation, not something you entered." },
    ],
    tips: ["Fix any highlighted problems first. Required inputs must be complete before the assessment can run.", "Blank optional inputs are never filled with assumed values."],
    whatHappensNext: "GreenFleet will compare the technologies using the same transport duty and show the results.",
  },
  "results.overview": {
    id: "results.overview",
    title: "How to interpret your results",
    shortDescription: "Four separate answers to four different questions.",
    whatYouAreDoing: "You are reading the outcome of the assessment you ran.",
    whatGreenFleetDoes: "GreenFleet presents separate dimensions: 1. Economic Performance, 2. Operational Feasibility, 3. Environmental Performance, 4. Commercial Viability.",
    whyItMatters: "These dimensions answer different questions and should not be interpreted as interchangeable. A cheaper option may not suit your routes, and a cleaner option may not pay for itself.",
    tips: ["Start with the commercial classification cards at the top, then open Why this result? to see the reasoning.", "Change an input and the results update. Nothing is stored apart from your inputs."],
    warnings: ["Results are model-based conclusions under your assumptions. They are not a forecast or investment advice."],
    links: [{ label: "Review inputs", href: "/assessment/review" }, { label: "View full methodology", href: "/methodology" }],
  },
  "results.economic": {
    id: "results.economic",
    title: "Economic results",
    shortDescription: "What each option costs, and whether the alternatives pay for themselves.",
    definitions: [
      { term: "Total cost of ownership (TCO)", text: "The estimated total cost of owning and operating the technology over the selected analysis horizon." },
      { term: "Present cost", text: "The value today of future costs after applying the selected discount rate." },
      { term: "Cost per km", text: "Estimated lifecycle cost divided by distance travelled." },
      { term: "Incremental NPV vs diesel", text: "The present-value economic advantage or disadvantage of choosing the alternative instead of diesel." },
      { term: "Positive NPV", text: "An economic advantage over diesel under the entered assumptions." },
      { term: "Negative NPV", text: "An economic disadvantage compared with diesel under the entered assumptions." },
      { term: "Payback", text: "How long cumulative savings take to recover the additional investment." },
      { term: "Discounted payback", text: "Payback after recognising the time value of money." },
    ],
    tips: ["If an alternative is cheaper to buy than diesel, payback is shown as immediate."],
    warnings: ["Costs are in the currency and units you entered. Tax, revenue and financing are not part of these figures."],
    links: [{ label: "View full methodology", href: "/methodology" }],
  },
  "results.operational": {
    id: "results.operational",
    title: "Operational feasibility",
    shortDescription: "Can the option do the transport work you described?",
    definitions: [
      { term: "SUITABLE", text: "No material operational constraint identified from available inputs." },
      { term: "CONDITIONAL", text: "Operation appears possible but depends on a stated condition." },
      { term: "CONSTRAINED", text: "A material entered constraint conflicts with the required duty." },
      { term: "INSUFFICIENT DATA", text: "Critical operational evidence is missing." },
    ],
    whatYouAreDoing: "For battery electric vehicles GreenFleet checks range against daily distance, route distance against range, charging, and payload. For biofuel it checks fuel availability, infrastructure and the refuelling burden.",
    tips: ["Operational checks use no prices. A cheap option can still be constrained.", "Optional inputs left blank are listed as not assessed. They do not lower the status."],
    whyItMatters: "Operational status is separate from economics, so a favourable NPV never hides a route the vehicle cannot complete.",
  },
  "results.environmental": {
    id: "results.environmental",
    title: "Environmental performance",
    shortDescription: "Estimated operational emissions, from factors you supply.",
    whatGreenFleetDoes: "GreenFleet estimates operational energy/fuel-related greenhouse-gas emissions only when compatible emission factors are supplied.",
    definitions: [
      { term: "CO2e", text: "Carbon dioxide equivalent. Different greenhouse gases expressed as the amount of CO2 with the same warming effect." },
      { term: "Emission factor", text: "The kilograms of CO2e released per litre of fuel or per kWh of electricity. It comes from a source you name." },
      { term: "tCO2e per year", text: "Tonnes of CO2e emitted by the whole fleet in a year." },
      { term: "kg CO2e per km", text: "Emissions divided by distance driven." },
      { term: "Change vs diesel", text: "How much lower or higher an alternative's emissions are than diesel's, as an amount and a percentage." },
    ],
    warnings: ["Missing environmental data are shown as unavailable, not zero.", "Vehicle manufacturing, battery manufacturing and infrastructure embodied emissions are outside the current scope unless future methodology adds them."],
    tips: ["Environmental performance is reported beside the commercial classification and does not change it."],
  },
  "results.commercial": {
    id: "results.commercial",
    title: "Commercial viability",
    shortDescription: "The classification of each alternative against diesel, under Policy v1.0.",
    definitions: [
      { term: "VIABLE", text: "Favourable economic case and no identified material unresolved operational constraint." },
      { term: "CONDITIONALLY VIABLE", text: "Potentially credible commercial case, but one or more conditions or material uncertainties must be resolved." },
      { term: "NOT YET VIABLE", text: "Current assumptions do not establish a sufficiently credible commercial case." },
      { term: "INSUFFICIENT EVIDENCE", text: "Essential information required for a defensible classification is missing." },
    ],
    whatGreenFleetDoes: "A fixed set of ordered rules decides the label. There is no score and no weighting. Diesel is the baseline and is not classified.",
    warnings: ["Environmental performance is reported separately and does not determine the commercial classification under Policy v1.0.", "A label is decision support under your assumptions. It is not investment advice."],
    tips: ["NOT YET VIABLE means the result may change if key assumptions change. A later stage will show which ones."],
    links: [{ label: "Read the policy", href: "/methodology" }],
  },
  "results.why": {
    id: "results.why",
    title: "Why this result?",
    shortDescription: "How to read the decision trace.",
    whatGreenFleetDoes: "The decision trace shows the exact rules GreenFleet followed to reach the classification.",
    definitions: [
      { term: "Evidence gate", text: "Is there enough information to judge? Missing critical items stop the process with INSUFFICIENT EVIDENCE." },
      { term: "Operational gate", text: "Can the option do the duty? An unresolved hard constraint stops it from being viable." },
      { term: "Economic gate", text: "Is the economic case favourable, near break-even or unfavourable?" },
      { term: "Conditions", text: "Things that must be arranged for the option to work, such as daytime charging." },
      { term: "Uncertainties", text: "Unknowns that could change the cost, such as an unknown battery replacement." },
      { term: "Hard constraints", text: "Entered facts that conflict with the duty and have no remedy in what you entered." },
      { term: "Reason codes", text: "Short labels for each reason, so the same reasons can be compared across assessments." },
    ],
    tips: ["Read the trace from the top. Each line is one step."],
  },
  methodology: {
    id: "methodology",
    title: "Methodology",
    shortDescription: "The formulas, assumptions and decision rules.",
    whatYouAreDoing: "You are reading how GreenFleet reaches its answers, in full technical detail.",
    whyItMatters: "Anyone should be able to check how a number or a label was produced.",
    tips: ["Help explains how to use the tool. This page explains how it works.", "Sections open and close. The commercial viability policy is open first."],
  },
  sensitivity: {
    id: "sensitivity",
    title: "Sensitivity analysis",
    shortDescription: "Coming in a later stage.",
    whatYouAreDoing: "Sensitivity analysis will allow you to examine how changing key assumptions affects the result.",
    warnings: ["This tool is not available yet. Nothing on this page calculates anything."],
    whatHappensNext: "For now, you can change inputs in the assessment and read the updated results.",
    links: [{ label: "Go to Results", href: "/results" }],
  },
  scenarios: {
    id: "scenarios",
    title: "Saved scenarios",
    shortDescription: "Coming in a later stage.",
    whatYouAreDoing: "Saved scenarios will allow you to keep different sets of assumptions and compare them.",
    warnings: ["This tool is not available yet. Nothing is saved on this page."],
    whatHappensNext: "For now, your single assessment is saved in this browser as you work.",
    links: [{ label: "Go to Overview", href: "/overview" }],
  },
  about: {
    id: "about",
    title: "About GreenFleet",
    shortDescription: "What the prototype is and is not.",
    whatYouAreDoing: "You are reading about the project.",
    tips: ["GreenFleet is built to make assumptions visible, so users can test them."],
    warnings: [DISCLAIMER],
  },
};

export const HELP_TOPICS: readonly HelpTopic[] = [
  { id: "getting-started", title: "Getting Started", entries: ["home"] },
  { id: "fleet-data", title: "Entering Fleet Data", entries: ["assessment.business"] },
  { id: "diesel", title: "Diesel Baseline", entries: ["assessment.diesel"] },
  { id: "bev", title: "Battery Electric Vehicles", entries: ["assessment.bev"] },
  { id: "biofuel", title: "Biofuel", entries: ["assessment.biofuel"] },
  { id: "finance", title: "Finance & Infrastructure", entries: ["assessment.finance", "assessment.review"] },
  { id: "results", title: "Understanding Results", entries: ["results.overview", "results.economic", "results.operational", "results.environmental"] },
  { id: "commercial", title: "Commercial Viability", entries: ["results.commercial", "results.why"] },
  { id: "methodology", title: "Methodology", entries: ["methodology", "sensitivity", "scenarios"] },
];

export const FINANCE_NOTE_TEXT = FINANCE_NOTE;
